limit_req_zone $binary_remote_addr zone=mylimit:10m rate=30r/s;

server {
    listen 80;
    server_name _;

    limit_req zone=mylimit burst=200 nodelay;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1000;

    location ~* \.(png|jpg|jpeg|mp3|mp4|ico)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /index.html;
}
